### ISSUE TITLE
Sickchill on rasberry pi 3 doesn't show the tv shows

### ISSUE THREAD

**Issue by jandrop** [linuxserver/docker-sickchill#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Show should be shown in the SickChill Dashboard

## Current Behavior
Show doesn't shown in the SickChill Dashboard

## Steps to Reproduce

1. Click shows and then click add shows
2. Search for a show and select it
3. Click add show button

## Environment
**OS:**  Raspbian     
**CPU architecture:** arm32     
**How docker service was installed:**      

```
$ curl -fsSL https://get.docker.com -o get-docker.sh
$ sh get-docker.sh
```
## Command used to create docker container (run/create/compose/screenshot)

```
sickrage:
    image: linuxserver/sickchill
    container_name: sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
    - /media/usb/sickrage/data:/config
    - /media/usb/transmission/downloads:/downloads
    - /media/usb/transmission/watch:/watch
    - /media/usb/tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
```

## Docker logs

```
 19:46:55 ERROR::SHOWQUEUE-ADD :: Error with theTVDB, not creating episode list: Unknown error while authentica   │
│   ting. Check your api key or your user/userkey                                                                    │
│   Traceback (most recent call last):                                                                               │
│     File "/app/sickchill/sickbeard/show_queue.py", line 491, in run                                                │
│       self.show.loadEpisodesFromIndexer()                                                                          │
│     File "/app/sickchill/sickbeard/tv.py", line 542, in loadEpisodesFromIndexer                                    │
│       show_episode.loadFromIndexer(*season_episode)                                                                │
│     File "/app/sickchill/sickbeard/tv.py", line 1565, in loadFromIndexer                                           │
│       myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)                          │
│     File "/app/sickchill/sickchill/show/indexers/wrappers.py", line 44, in wrapper                                 │
│       result = target(*args, **kwargs)                                                                             │
│     File "/app/sickchill/sickchill/show/indexers/tvdb.py", line 110, in episode                                    │
│       result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang   │
│   , **kwargs).all()[0]                                                                                             │
│     File "/app/sickchill/lib/tvdbsimple/series.py", line 222, in all                                               │
│       for i in range (1, self.pages()+1):                                                                          │
│     File "/app/sickchill/lib/tvdbsimple/series.py", line 201, in pages                                             │
│       self.page(1)                                                                                                 │
│     File "/app/sickchill/lib/tvdbsimple/series.py", line 244, in page                                              │
│       response = self._GET(path, params=filters, cleanJson=False)                                                  │
│     File "/app/sickchill/lib/tvdbsimple/base.py", line 149, in _GET                                                │
│       return self._request('GET', path, params=params, cleanJson=cleanJson)                                        │
│     File "/app/sickchill/lib/tvdbsimple/base.py", line 142, in _request                                            │
│       return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)           │
│     File "/app/sickchill/lib/tvdbsimple/base.py", line 126, in _request                                            │
│       self._set_token_header(forceNewToken)                                                                        │
│     File "/app/sickchill/lib/tvdbsimple/base.py", line 91, in _set_token_header                                    │
│       self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)                                        │
│     File "/app/sickchill/lib/tvdbsimple/base.py", line 122, in get_token                                           │
│       raise AuthenticationError(error)                                                                             │
│   AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
```

**Comment by aptalca** [comment]
Closing as it is really old. Feel free to reopen if needed
