### ISSUE TITLE
Fails to start new container

### ISSUE THREAD

**Issue by gadgetusaf** [linuxserver/docker-sickchill#21]
Docker application fails to start when using cifs volumes 

------------------------------

## Expected Behavior
Docker container to start webserver and application

## Current Behavior
webserver fails to start

## Steps to Reproduce

1. docker volume create --driver local --opt type=cifs --opt device="some path" --opt o=user=use,domain=domain,password=password moviesout
2. docker volume create --driver local --opt type=cifs --opt device="some path" --opt o=user=user,domain=domain,password=password moviesin
3. docker create --name=couchpotato -v D:\Docker\CouchPotato1:/config -v moviesin:/downloads -v moviesout:/movies -e TZ=America/New_York -p 5050:5050 linuxserver/couchpotat
4. start container

## Environment
**OS:** Windows 10       
**CPU architecture:** x86_64      
**How docker service was installed:**   As a service   

## Command used to create docker container (run/create/compose/screenshot)
see above

## Docker logs
`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing...

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing...

usermod: no changes

-------------------------------------

_ ()

| | ___ _ __

| | / __| | | / \

| | \__ \ | | | () |

|_| |___/ |_| \__/

Brought to you by linuxserver.io

We gratefully accept donations at:

https://www.linuxserver.io/donate/

GID/UID

User uid: 911

User gid: 911

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing...

[cont-init.d] 30-config: exited 0.

[cont-init.d] 99-custom-files: executing...

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Traceback (most recent call last):

File "/app/couchpotato/CouchPotato.py", line 135, in <module>

l.run()

File "/app/couchpotato/CouchPotato.py", line 89, in run

runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)

File "/app/couchpotato/couchpotato/runner.py", line 145, in runCouchPotato

db.create()

File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner

res = f(*args, **kwargs)

File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 99, in create

res = super(SuperThreadSafeDatabase, self).create(*args, **kwargs)

File "/app/couchpotato/libs/CodernityDB/database.py", line 529, in create

self.__open_new(**kwargs)

File "/app/couchpotato/libs/CodernityDB/database.py", line 481, in __open_new

self.add_index(id_ind, create=False)

File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 105, in add_index

res = super(SuperThreadSafeDatabase, self).add_index(*args, **kwargs)

File "/app/couchpotato/libs/CodernityDB/database.py", line 331, in add_index

ind_obj, name = self.__write_index(new_index, _next, edit=False)

File "/app/couchpotato/libs/CodernityDB/database.py", line 303, in __write_index

ind_obj = self._read_index_single(p, ind_path + '.py', ind_kwargs)

File "/app/couchpotato/libs/CodernityDB/database.py", line 197, in _read_index_single

name = f.readline()[2:].strip()

IOError: [Errno 38] Function not implemented

File "/usr/lib/python2.7/logging/__init__.py", line 889, in emit

stream.write(fs % msg)

Logged from file logger.py, line 50

File "/app/couchpotato/couchpotato/runner.py", line 138, in runCouchPotato

zipf.add(os.path.join(root, zfilename), arcname = 'database/%s' % os.path.join(root[len(db_path) + 1:], zfilename))

File "/usr/lib/python2.7/tarfile.py", line 2025, in add

self.addfile(tarinfo, f)

File "/usr/lib/python2.7/tarfile.py", line 2054, in addfile

copyfileobj(fileobj, self.fileobj, tarinfo.size)

File "/usr/lib/python2.7/tarfile.py", line 278, in copyfileobj

buf = src.read(remainder)

`

**Comment by gadgetusaf** [comment]
2nd note I can see the data in the mounted volumes.
