### ISSUE TITLE
Latest image fails to run with imdb module error

### ISSUE THREAD

**Issue by XanderStrike** [linuxserver/docker-sickchill#26]
## Expected Behavior
Container deploys successfully, 

## Current Behavior
Process fails to start with the following error:

```
Traceback (most recent call last):
  File "/usr/bin/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/lib/python3.8/site-packages/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/usr/lib/python3.8/site-packages/sickchill/tv.py", line 15, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
```

## Steps to Reproduce
1. Deploy using the run command below
2. Observe logs show error
3. Observe no successful connections to exposed port

## Environment
**OS:** Ubuntu 20.04     
**CPU architecture:** x86_64
**How docker service was installed:**  `apt`

## Command used to create docker container (run/create/compose/screenshot)
```
#!/bin/bash
docker run \
  --name=sickchill \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 8081:8081 \
  -v /tmp/config:/config \
  -v /tmp/downloads:/downloads \
  -v /tmp/tv:/tv \
  --restart unless-stopped \
  linuxserver/sickchill:latest
```

## Notes

**The tag 2020.9.13.post1-ls42 works fine, so this is a recent change**

Question, do your pipelines that update config do any smoke testing? This image has failed to upgrade cleanly twice in the last couple weeks, a small smoke test just to make sure the container accepts http connections on the exposed port would have prevented both this and #22 from going to live in a broken state. I'm happy to help contribute that if you can point me to the pipelines.

## Docker logs

<details>
<summary>Click to expand!</summary>

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
SickChill: https://www.patreon.com/SickChill

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Setting permissions
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/usr/lib/python3.8/site-packages/sickchill/locale
/usr/lib/python3.8/site-packages/sickchill/locale
Traceback (most recent call last):
  File "/usr/bin/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/lib/python3.8/site-packages/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/usr/lib/python3.8/site-packages/sickchill/tv.py", line 15, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
/usr/lib/python3.8/site-packages/sickchill/locale
/usr/lib/python3.8/site-packages/sickchill/locale
Traceback (most recent call last):
  File "/usr/bin/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/lib/python3.8/site-packages/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/usr/lib/python3.8/site-packages/sickchill/tv.py", line 15, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
</details>

**Comment by XanderStrike** [comment]
Closing in favor of #25
