### ISSUE TITLE
2022.2.20-ls87: Help & Info page is broken

### ISSUE THREAD

**Issue by LapinFou** [linuxserver/docker-sickchill#39]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
That the page "Help & Info" should be display. 😊
I'm referring to this page: http://SERVER_IP:PORT/config/

## Steps to Reproduce
When clicking on the **wheel settings**, then **Help & info**, I got this error message:
```
FixME

A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes. 
```
```
Traceback (most recent call last):
                    File /usr/lib/python3.9/site-packages/sickchill/views/index.py:188, in async_call:
                        return function(**kwargs)
                    File /usr/lib/python3.9/site-packages/tornado/web.py:1905, in wrapper:
                        return method(self, *args, **kwargs)
                    File /usr/lib/python3.9/site-packages/sickchill/views/config/index.py:61, in index:
                        sc_version = updater.updater.get_clean_version()
                AttributeError: 'NoneType' object has no attribute 'get_clean_version'
```

## Environment
**OS:** Linux (Synology DSM7)
**CPU architecture:** x86_64
**How docker service was installed:** through Portainer with this image lscr.io/linuxserver/sickchill

**Comment by aptalca** [comment]
Just tested latest here with a fresh install and it all works fine, no errors. It displays the sickchill info:
```
Install: [pip](https://anonym.to/?https://pypi.org/project/sickchill/)
Version: [v2022.02.20](https://anonym.to/?https://github.com/SickChill/SickChill/releases/tag/v2022.02.20)
Database Version: 44.5
```

**Comment by LapinFou** [comment]
I updated to the latest version through Portainer.
Will try to download again the image. For the record, it was working fine with the N-1 version.
The conf has been backup. So, I can always roll-back if something went wrong during the update.
I will keep you inform ASAP I'm back at home. 😊

Here is a snapshot of the error:
![image](https://user-images.githubusercontent.com/1685030/157902006-ad566057-788c-421f-ad5d-08dd6531595e.png)

**Comment by LapinFou** [comment]
Back at home.

I killed the latest image and recreate the container.
This time, everything is working despite the following error message in the docker log:
```
2022-03-11 19:01:16,053 CRITICAL [imdbpy] /usr/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find?q=Homestead+Rescue%3A+Raney+Ranch+%282020%29&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')},); kwds: {}
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 221, in retrieve_unicode
    content = response.read()
  File "/usr/lib/python3.9/http/client.py", line 469, in read
    return self._readall_chunked()
  File "/usr/lib/python3.9/http/client.py", line 576, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.9/http/client.py", line 559, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.9/http/client.py", line 519, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```
This probably a SickChill issue, not an LinuxServer image issue. 😄
